name: Build Workflow
on:
  push:

jobs:
  cache_checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
  build:
    runs-on: ubuntu-latest
    needs: cache_checkout
    steps:
      - name: Build
        run: pnpm build


  test:
    runs-on: ubuntu-latest
    needs: cache_checkout
    steps:
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test